/* See LICENSE file for license and copyright information */

#ifndef SYSFILTER_MODULE_H
#define SYSFILTER_MODULE_H

#include <stddef.h>

#define SYSFILTER_DEVICE_NAME "sysfilter"
#define SYSFILTER_DEVICE_PATH "/dev/" SYSFILTER_DEVICE_NAME

#define SYSFILTER_IOCTL_MAGIC_NUMBER (long)0x1248

#define SYSFILTER_IOCTL_CMD_BLOCK \
  _IOR(SYSFILTER_IOCTL_MAGIC_NUMBER, 1, size_t)

#define SYSFILTER_IOCTL_CMD_PID \
  _IOR(SYSFILTER_IOCTL_MAGIC_NUMBER, 2, size_t)

#define SYSFILTER_IOCTL_CMD_UNBLOCK \
  _IOR(SYSFILTER_IOCTL_MAGIC_NUMBER, 3, size_t)

#define SYSFILTER_IOCTL_CMD_WRITEKEY \
  _IOR(SYSFILTER_IOCTL_MAGIC_NUMBER, 4, size_t)

#define SYSFILTER_IOCTL_CMD_KILL_ON_VIOLATION \
  _IOR(SYSFILTER_IOCTL_MAGIC_NUMBER, 5, size_t)

  #endif // SYSFILTER_MODULE_H
